language: node_js
node_js:
- 10
cache:
  npm: true
  directories:
  - ~/.cache

deploy:
  skip_cleanup: true
  provider: surge
  project: ./dist/
  domain: cryptical.surge.sh

script:
- npm run build
- npm run dev
- sleep 20
- npm run test
